services:
  - type: web
    name: iot-cloud-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DEVICE_API_KEY
        sync: false
      - key: AIO_USERNAME
        sync: false
      - key: AIO_KEY
        sync: false
      - key: AIO_STATE_FEED
        value: detector-incendios.estado
      - key: VAPID_SUBJECT
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
