/**
 * @fileoverview Machine-learning inference service for IoT sensor analysis.
 *
 * Provides three analysis functions:
 *   - clasificarRiesgo   Classifies fire/gas risk using a trained ONNX model.
 *   - detectarAnomalia   Flags statistically anomalous sensor readings.
 *   - predecirTendencia  Estimates whether gas levels are rising or falling.
 *
 * Models are loaded lazily on first use so the module can be imported before
 * the files exist. When models are absent the service falls back to
 * deterministic rule-based logic and emits a warning via the logger.
 *
 * Model files (generated by scripts/train_model.py, committed to git):
 *   models/risk_classifier.onnx
 *   models/anomaly_params.json
 */

'use strict';

const path   = require('path');
const fs     = require('fs');
const logger = require('../logger');

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const MODELS_DIR          = path.join(__dirname, '..', 'models');
const CLASSIFIER_MODEL    = path.join(MODELS_DIR, 'risk_classifier.onnx');
const ANOMALY_PARAMS_FILE = path.join(MODELS_DIR, 'anomaly_params.json');

// ---------------------------------------------------------------------------
// Risk label mapping — must match the integer encoding in train_model.py.
// ---------------------------------------------------------------------------

const RISK_LABELS = ['normal', 'medio', 'alto'];

// ---------------------------------------------------------------------------
// Lazy singletons
// ---------------------------------------------------------------------------

/** @type {object | null | undefined} undefined = not yet attempted */
let _ort = undefined;

/** @type {object | null} */
let _classifierSession = null;

/** @type {{ mean: number[], std: number[], threshold: number } | null} */
let _anomalyParams = null;

/**
 * Load (or return the cached) onnxruntime-node module.
 * Returns null when the package is not installed so callers can fall back
 * gracefully without crashing the process.
 *
 * @returns {object | null}
 */
function getOrt() {
  if (_ort !== undefined) return _ort || null;

  try {
    // Dynamic require keeps the module optional — the app boots fine without it.
    // eslint-disable-next-line global-require
    _ort = require('onnxruntime-node');
  } catch (err) {
    logger.warn(
      'onnxruntime-node is not installed — falling back to rule-based inference.',
      err.message,
    );
    _ort = null;
  }

  return _ort;
}

/**
 * Load (or return the cached) ONNX inference session for risk classification.
 *
 * @returns {Promise<object | null>}
 */
async function getClassifierSession() {
  if (_classifierSession) return _classifierSession;

  const ort = getOrt();
  if (!ort) return null;

  if (!fs.existsSync(CLASSIFIER_MODEL)) {
    logger.warn(
      'risk_classifier.onnx not found — run scripts/train_model.py and commit models/.',
    );
    return null;
  }

  try {
    _classifierSession = await ort.InferenceSession.create(CLASSIFIER_MODEL);
  } catch (err) {
    logger.error('Failed to load risk_classifier.onnx', err.message);
    _classifierSession = null;
  }

  return _classifierSession;
}

/**
 * Load (or return the cached) anomaly detection parameters from JSON.
 *
 * @returns {{ mean: number[], std: number[], threshold: number } | null}
 */
function getAnomalyParams() {
  if (_anomalyParams) return _anomalyParams;

  if (!fs.existsSync(ANOMALY_PARAMS_FILE)) {
    logger.warn(
      'anomaly_params.json not found — anomaly detection will be skipped.',
    );
    return null;
  }

  try {
    _anomalyParams = JSON.parse(fs.readFileSync(ANOMALY_PARAMS_FILE, 'utf8'));
  } catch (err) {
    logger.error('Failed to parse anomaly_params.json', err.message);
    _anomalyParams = null;
  }

  return _anomalyParams;
}

// ---------------------------------------------------------------------------
// Rule-based fallback
// ---------------------------------------------------------------------------

// Rule-based thresholds (12-bit ESP32 ADC, range 0-4095).
// Calibrated to observed clean-air baseline of ~550 ADC.
// Must match the values in scripts/generate_synthetic.py and export_data.py.
const ALTO_GAS_THRESHOLD  = 1800;
const MEDIO_GAS_THRESHOLD = 1100;

// Motion encoding: main.cpp transmits !digitalRead(MOVE_PIN).
//   movimiento = 0  -> motion detected
//   movimiento = 1  -> no motion (idle state)
const MOTION_DETECTED = 0;

/**
 * Deterministic rule-based classifier used when the ONNX model is unavailable.
 * Thresholds match those used to generate synthetic training data.
 *
 * @param {{ llama: number, gas: number, movimiento: number }} reading
 * @returns {string} "normal" | "medio" | "alto"
 */
function ruleBasedRisk({ llama, gas, movimiento }) {
  if (llama === 1 || gas > ALTO_GAS_THRESHOLD)              return 'alto';
  if (movimiento === MOTION_DETECTED || gas > MEDIO_GAS_THRESHOLD) return 'medio';
  return 'normal';
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Classify the risk level for a set of sensor readings.
 *
 * Uses the ONNX RandomForestClassifier when available; otherwise falls back
 * to deterministic rule-based logic so the endpoint always returns a result.
 *
 * @param {{ llama: number, gas: number, movimiento: number }} reading
 * @returns {Promise<string>} "normal" | "medio" | "alto"
 */
async function clasificarRiesgo({ llama, gas, movimiento }) {
  const ort     = getOrt();
  const session = ort ? await getClassifierSession() : null;

  if (!session) {
    return ruleBasedRisk({ llama, gas, movimiento });
  }

  const inputTensor = new ort.Tensor(
    'float32',
    new Float32Array([llama, gas, movimiento]),
    [1, 3],
  );

  const feeds   = { [session.inputNames[0]]: inputTensor };
  const results = await session.run(feeds);

  // skl2onnx encodes integer labels as BigInt64 on some platforms.
  const rawLabel = results[session.outputNames[0]].data[0];
  const index    = typeof rawLabel === 'bigint' ? Number(rawLabel) : rawLabel;

  return RISK_LABELS[index] ?? 'normal';
}

/**
 * Detect whether the current reading is statistically anomalous.
 *
 * Uses a per-feature Z-score method against the training set distribution
 * computed by scripts/train_model.py. A reading is flagged anomalous when
 * any feature deviates beyond the trained threshold.
 *
 * @param {{ llama: number, gas: number, movimiento: number }} reading
 * @returns {boolean} true if the reading is anomalous
 */
function detectarAnomalia({ llama, gas, movimiento }) {
  const params = getAnomalyParams();
  if (!params) return false;

  const features = [llama, gas, movimiento];
  const zScores  = features.map((val, i) =>
    params.std[i] > 0 ? Math.abs((val - params.mean[i]) / params.std[i]) : 0,
  );

  return Math.max(...zScores) > params.threshold;
}

/**
 * Predict gas concentration trend from recent readings using OLS linear
 * regression on the gas feature.
 *
 * @param {Array<{ gas: number }>} lecturas
 *   Recent readings, newest first (as returned by a Firestore desc query).
 *   Minimum 3 items for a reliable estimate; returns "estable" for shorter
 *   arrays.
 * @returns {"estable" | "subiendo" | "bajando"}
 */
function predecirTendencia(lecturas) {
  if (!Array.isArray(lecturas) || lecturas.length < 3) return 'estable';

  // Reverse to chronological order so index 0 = oldest reading.
  const y = [...lecturas].reverse().map((l) => Number(l.gas));
  const n = y.length;
  const x = y.map((_, i) => i);

  const sumX  = x.reduce((a, b) => a + b, 0);
  const sumY  = y.reduce((a, b) => a + b, 0);
  const sumXY = x.reduce((acc, xi, i) => acc + xi * y[i], 0);
  const sumX2 = x.reduce((acc, xi) => acc + xi * xi, 0);

  const denominator = n * sumX2 - sumX * sumX;
  if (denominator === 0) return 'estable';

  const slope = (n * sumXY - sumX * sumY) / denominator;

  // Change of >= 10 ADC units per reading is classified as a trend.
  const TREND_THRESHOLD = 10;
  if (slope >  TREND_THRESHOLD) return 'subiendo';
  if (slope < -TREND_THRESHOLD) return 'bajando';
  return 'estable';
}

module.exports = { clasificarRiesgo, detectarAnomalia, predecirTendencia };
