"""
train_model.py
--------------
Trains and exports ML models for IoT sensor analysis.

Input CSV files (auto-detected, at least one must exist):
    scripts/synthetic_data.csv  -- generated by generate_synthetic.py
    scripts/real_data.csv       -- generated by export_data.py (optional)

Outputs (written to models/):
    risk_classifier.onnx   -- RandomForestClassifier (0=normal, 1=medio, 2=alto)
    anomaly_params.json    -- Per-feature mean, std, and Z-score threshold
                              used by the Node.js anomaly detection function.

The ONNX classifier is consumed by services/ml.service.js via onnxruntime-node.
The anomaly params are loaded as plain JSON; no ONNX runtime needed for them.

Usage:
    cd scripts
    pip install -r requirements.txt
    python generate_synthetic.py        # run once to create synthetic_data.csv
    python export_data.py               # optional: adds real Firestore data
    python train_model.py               # trains and writes models/
    # Commit the generated models/ files to git so Railway can use them.
"""

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from skl2onnx import to_onnx
from skl2onnx.common.data_types import FloatTensorType

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPTS_DIR = Path(__file__).parent
MODELS_DIR  = SCRIPTS_DIR.parent / "models"

SYNTHETIC_CSV = SCRIPTS_DIR / "synthetic_data.csv"
REAL_CSV      = SCRIPTS_DIR / "real_data.csv"

CLASSIFIER_ONNX    = MODELS_DIR / "risk_classifier.onnx"
ANOMALY_PARAMS_JSON = MODELS_DIR / "anomaly_params.json"

# ---------------------------------------------------------------------------
# Anomaly detection configuration
# ---------------------------------------------------------------------------

# Number of standard deviations beyond which a reading is considered anomalous.
# Lower values = more sensitive. Adjust based on acceptable false-positive rate.
ANOMALY_Z_THRESHOLD = 2.5

# Feature order must match the input order used in ml.service.js.
FEATURES = ["llama", "gas", "movimiento"]
LABEL_NAMES = ["normal", "medio", "alto"]


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_training_data() -> pd.DataFrame:
    """
    Load and merge all available CSV files.
    Exits with a clear message if no CSV is found.
    """
    frames = []
    for csv_path in (SYNTHETIC_CSV, REAL_CSV):
        if csv_path.exists():
            df = pd.read_csv(csv_path)
            frames.append(df)
            print(f"  Loaded {len(df):>5} rows from {csv_path.name}")
        else:
            print(f"  Skipping {csv_path.name} (not found)")

    if not frames:
        print("\nERROR: No training data found.")
        print("Run generate_synthetic.py first:\n  python generate_synthetic.py")
        sys.exit(1)

    combined = pd.concat(frames, ignore_index=True).dropna()
    print(f"\n  Total samples after merge: {len(combined)}")
    print(combined["label"].value_counts().rename(dict(enumerate(LABEL_NAMES))).to_string())
    return combined


# ---------------------------------------------------------------------------
# Model training
# ---------------------------------------------------------------------------

def train_classifier(
    X_train: np.ndarray,
    y_train: np.ndarray,
) -> RandomForestClassifier:
    """
    Train a RandomForestClassifier with balanced class weights to handle
    the natural imbalance between normal and alarm events.
    """
    clf = RandomForestClassifier(
        n_estimators=100,
        max_depth=8,
        random_state=42,
        class_weight="balanced",
        n_jobs=-1,
    )
    clf.fit(X_train, y_train)
    return clf


def compute_anomaly_params(X_train: np.ndarray) -> dict:
    """
    Compute per-feature statistics from the training distribution.
    The resulting JSON is used by the Node.js Z-score anomaly detector.
    """
    return {
        "mean":      X_train.mean(axis=0).tolist(),
        "std":       X_train.std(axis=0).tolist(),
        "threshold": ANOMALY_Z_THRESHOLD,
        "features":  FEATURES,
    }


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------

def export_classifier(clf: RandomForestClassifier) -> None:
    """Convert the trained classifier to ONNX and write it to disk."""
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    # Input type: one row of [llama, gas, movimiento] as float32.
    initial_type = [("X", FloatTensorType([None, len(FEATURES)]))]
    onnx_model   = to_onnx(clf, initial_types=initial_type, target_opset=12)

    with open(CLASSIFIER_ONNX, "wb") as fh:
        fh.write(onnx_model.SerializeToString())

    size_kb = CLASSIFIER_ONNX.stat().st_size / 1024
    print(f"\n  Classifier  -> {CLASSIFIER_ONNX}  ({size_kb:.1f} KB)")


def export_anomaly_params(params: dict) -> None:
    """Write the anomaly detection parameters as a JSON file."""
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    with open(ANOMALY_PARAMS_JSON, "w", encoding="utf-8") as fh:
        json.dump(params, fh, indent=2)

    print(f"  Anomaly params -> {ANOMALY_PARAMS_JSON}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    print("=== Loading training data ===")
    df = load_training_data()

    X = df[FEATURES].values.astype(np.float32)
    y = df["label"].values.astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    print("\n=== Training RandomForestClassifier ===")
    clf = train_classifier(X_train, y_train)

    y_pred = clf.predict(X_test)
    print("\nClassification report (test set):")
    print(classification_report(y_test, y_pred, target_names=LABEL_NAMES))

    anomaly_params = compute_anomaly_params(X_train)

    print("=== Exporting models ===")
    export_classifier(clf)
    export_anomaly_params(anomaly_params)

    print("\nDone. Commit the contents of models/ to your git repository")
    print("so Railway can load the files at runtime.")


if __name__ == "__main__":
    main()
